{"name": "test_m1", "status": "failed", "statusDetails": {"message": "AssertionError: Failed case\nassert 2 == 3\n  +2\n  -3", "trace": "def test_m1():\n        x=2\n        y=3\n>       assert x==y , \"Failed case\"\nE       AssertionError: Failed case\nE       assert 2 == 3\nE         +2\nE         -3\n\nTest_Sele.py:7: AssertionError"}, "start": 1611552361913, "stop": 1611552361914, "uuid": "155dce3e-586b-42f5-8d96-c38881b83c50", "historyId": "269e8ba5c29624af3e8a279b3451c564", "testCaseId": "f823f80446cd22bdc31c0df70d0a8c99", "fullName": "Test_Sele#test_m1", "labels": [{"name": "suite", "value": "Test_Sele"}, {"name": "host", "value": "WINVA185060-0WA"}, {"name": "thread", "value": "2304-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_Sele"}]}